"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) '''


[time]
format = '[son $time ](itallic yellow)'
use_12hr = true
disabled = false
